name: my_gallery
description: functional assembly


# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 分帧上屏
  keframe: ^2.0.3

  # 图表
  fl_chart: ^0.41.0

  # 录屏
  screen_recorder: ^0.0.3
  # 截屏
  screenshot: ^1.2.3
#  tencent_trtc_cloud: ^2.0.9
#  tencent_im_sdk_plugin: ^3.7.1

  # debug 调试工具 release模式要关上
  flutter_ume: ^0.3.0+1
  flutter_ume_kit_ui: ^0.3.0+1
  flutter_ume_kit_device: ^0.3.0
  flutter_ume_kit_perf: ^0.3.0
  flutter_ume_kit_show_code: ^0.3.0
  flutter_ume_kit_console: ^0.3.0
  flutter_ume_kit_dio: ^0.3.0

  # Service loader 框架 类似于中介者模式
  get_it: ^7.2.0
  # 随机颜色
  random_color: ^1.0.6-nullsafety

  # 广告融合集成
  flutter_universalad: ^1.0.10

  #  shared_preferences: ^2.0.5
  #  provider: ^5.0.0
  crypto: ^3.0.1
  #  dio: ^4.0.0
  #  badges: ^2.0.1
  flutter_bugly: ^0.4.3
  #  permission_handler: ^7.1.0
  #  fluttertoast: ^8.0.6
  #  url_launcher: ^6.0.3
  #  flutter_easyrefresh: ^2.1.8
  replay_kit_launcher: ^0.3.0
  flutter_styled_toast: ^2.0.0

  # 高德地图在项目中Android部分有些问题
  #  amap_flutter_map: ^3.0.0
  #  amap_flutter_location: ^3.0.0

  #    git:
  #      url: https://github.com/waitwalker/amap_flutter_location.git
  #      ref: 'main'
  #  amap_flutter_map:
  #    git:
  #      url: https://github.com/waitwalker/amap_flutter_map.git
  #      ref: 'main'

  #  azlistview: ^1.1.1
  # 滚动定位列表 按距离滚动到指定位置 按索引滚动到指定位置
  scrollable_positioned_list: ^0.2.3
  # 状态管理
  provider: ^6.0.2
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.9
  flutter_advanced_segment: ^2.0.1+1
  permission_handler: ^9.2.0
  flutter_easyrefresh: ^2.2.1
  url_launcher: ^6.0.20
  badges: ^2.0.2
  lpinyin: ^2.0.2
  # 全局事件总线
  event_bus:  ^2.0.0
  #webview
  webview_flutter: ^3.0.1
  # svg 加载工具
  flutter_svg: ^0.21.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  json_serializable: ^4.1.0


flutter:
  uses-material-design: true

  assets:
    - static/images/2.0x/
    - static/images/3.0x/
    - static/images/
    - static/svgs/
    - static/data/
    - assets/
    - assets/images/
    - assets/images/callingDemo/
    - assets/images/liveRoom/

  fonts:
    - family: aliIconFont
      fonts:
        - asset: static/font/iconfont.ttf


